### ISSUE TITLE
兼容性不好

### ISSUE THREAD

**Issue by muziling** [brvphoenix/luci-app-wrtbwmon#10]
用的是
https://github.com/coolsnowwolf/lede的OP， 2.0的IPK装上，直接报lua错误 打不开
改用1.6版本，可以打开 ，但是少引入了一个JS，参考：
https://github.com/openwrt/luci/pull/3716  加上后，样式也不正常， 感觉是样式名为 table-titles 等没定义导致的

**Comment by brvphoenix** [comment]
The version 2.0 has converted to js api for client-side rendering. Some non-official openwrt forks have no support for js api , for example, [coolsnowwolf's fork](https://github.com/coolsnowwolf/lede), and will not been compatible until they have updated the LuCI source to the official version up to 19.07.x.

You can refer to the official [LuCI source](https://github.com/openwrt/luci) for more information.

Besides, the cbi.js has been included in the [header.htm](https://github.com/openwrt/luci/blob/98a9d07d8998fae912ff43ee4d45ed8ad09aa04c/themes/luci-theme-bootstrap/luasrc/view/themes/bootstrap/header.htm#L37) for all official theme. I have verified that it has no compatible issues with the official release both 18.06.x and 19.07.x.

I can't guarantee it is compatible with all the non-official releases. However, you can modified the source yourself. Submitting a PR is also welcomed.
