### ISSUE TITLE
Whether the default displayed broadband and IP protocols can be written to the configuration file

### ISSUE THREAD

**Issue by tty228** [brvphoenix/luci-app-wrtbwmon#12]
Whether the default displayed broadband and IP protocols can be written to the configuration file.
Thank you.

**Comment by brvphoenix** [comment]
If written to the config file, the changes in the default value of the bandwidth and the protocol will trigger the wrtbwmon to restart.

I need to consider whether it can be avoided to trigger the restarting.

**Comment by tty228** [comment]
Thank you.
