### ISSUE TITLE
修改带宽（bandwidth）不能保存

### ISSUE THREAD

**Issue by tianchaomaker** [brvphoenix/luci-app-wrtbwmon#13]
如题，修改带宽后不能报错，刷新后又成默认的1M。希望作者能修复这个问题。万分感谢

**Comment by brvphoenix** [comment]
@tianchaomaker 
Currently, there is no ideal method to solve this issue.

If saving the value to config, some side effects can't be avoid, such as https://github.com/brvphoenix/luci-app-wrtbwmon/issues/12#issuecomment-606056538.

Besides, the config can also be saved in local storage, which I think is not the general behavior for the LuCI.

You can modified the codes bellow to modified the default value permanently.
https://github.com/brvphoenix/luci-app-wrtbwmon/blob/bc534c2c281e893696637d405f2a83e229965b43/luci-app-wrtbwmon/htdocs/luci-static/resources/view/wrtbwmon/details.js#L160
https://github.com/brvphoenix/luci-app-wrtbwmon/blob/bc534c2c281e893696637d405f2a83e229965b43/luci-app-wrtbwmon/htdocs/luci-static/resources/view/wrtbwmon/details.js#L471
