### ISSUE TITLE
Sort doesn't work

### ISSUE THREAD

**Issue by nixcamic** [brvphoenix/luci-app-wrtbwmon#14]
When sorting columns by Download or Upload the numerical value is used to sort not taking into account the units. So 140 B/s is more than 4 KB/s is more than 2 MB/s.

**Comment by brvphoenix** [comment]
@nixcamic 
Can you provide some screenshots?

**Comment by brvphoenix** [comment]
This should have been fixed by 2c79b24dd9c2f24db6e55ac0d0ce9aafbf3efe76. You can try this [artifact](https://github.com/brvphoenix/luci-app-wrtbwmon/suites/651302073/artifacts/5595499).

You can reopen this issue if it has not been resolved.
