### ISSUE TITLE
Does not work on new Openwrt releases

### ISSUE THREAD

**Issue by IceG2020** [brvphoenix/luci-app-wrtbwmon#15]
![Error](https://user-images.githubusercontent.com/59826889/80918897-845c2280-8d67-11ea-8d9b-4a8076109751.PNG)

P.S.
Colors downflow/upflow too dark / strong make reading the progress bar difficult.

**Comment by brvphoenix** [comment]
Try this [artifacts](https://github.com/brvphoenix/luci-app-wrtbwmon/suites/650235299/artifacts/5570810).
