### ISSUE TITLE
PermissionError from luci.js after installation

### ISSUE THREAD

**Issue by dbw9580** [brvphoenix/luci-app-wrtbwmon#17]
After installation I got `PermissionError`s in the browser console when no data was shown on the traffic status page. After restart `rpcd` the problem was resolved.

Maybe restart the `rpcd` in the post-installation script?

**Comment by brvphoenix** [comment]
Refer to https://github.com/openwrt/luci/commit/3c441efa02410d6e5a4d6f6719dcd6b848d7c2c9.

**Comment by dbw9580** [comment]
Thanks for the info.
