### ISSUE TITLE
Case insensitive MAC addresses in the Custom User File

### ISSUE THREAD

**Issue by sinancetinkaya** [brvphoenix/luci-app-wrtbwmon#21]
Current version doesn't recognize upper case MAC addresses

**Comment by brvphoenix** [comment]
@sinancetinkaya 
Have been fixed in 441b0a845b0340e7be1192dc6a8e2314ea6c070d.

Test on this [artifact](https://github.com/brvphoenix/luci-app-wrtbwmon/suites/795380001/artifacts/8522934).

**Comment by sinancetinkaya** [comment]
Tested the ipk file on the artifact link, it's not working. Uppercase MAC addresses don't show up in the list.

Besides, Kiougar's luci-wrtbwmon was pulling the host names from `/etc/config/dhcp` as well. Wouldn't be this a better approach?

**Comment by brvphoenix** [comment]
Current pre-released ipk is case insensitive in the custom user file. I have tested lower case, upper case and mixed case and erverthing is OK.

The dhcp is pulled from luci-rpc and it depends on the upstream OpenWrt whether it can be resolved from `/etc/config/dhcp`.

**Comment by sinancetinkaya** [comment]
The link of ipk you gave me is correct, right?
Because I tried uppercase Mac address and it didn't show up in the traffic
tab.

**Comment by brvphoenix** [comment]
https://github.com/brvphoenix/luci-app-wrtbwmon/releases/download/release-2.0.3/luci-app-wrtbwmon_2.0.3-1_all.ipk

**Comment by sinancetinkaya** [comment]
![image](https://user-images.githubusercontent.com/2675655/84726196-06f61580-af95-11ea-8788-9c2e7982b22f.png)
![image](https://user-images.githubusercontent.com/2675655/84726218-0fe6e700-af95-11ea-88e1-ddfd96b3ca3e.png)
![image](https://user-images.githubusercontent.com/2675655/84726299-3ad13b00-af95-11ea-8b55-258bcde4482d.png)

**Comment by sinancetinkaya** [comment]
OpenWrt SNAPSHOT r13573-03a0b7b7e5 / LuCI Master git-20.154.54590-05f07e5

**Comment by brvphoenix** [comment]
Test to cler the cache. If you are using chrome, press F12, check `Disable cache ` and refresh the page.
![screenshot](https://user-images.githubusercontent.com/30111323/84726570-c495fe00-afbf-11ea-95f3-68ec440f13cf.PNG)

**Comment by sinancetinkaya** [comment]
@brvphoenix I'm using Firefox
![image](https://user-images.githubusercontent.com/2675655/84772814-28322280-afe4-11ea-8289-652f12a70290.png)

**Comment by sinancetinkaya** [comment]
@brvphoenix I'm using Firefox
![image](https://user-images.githubusercontent.com/2675655/84772991-6deeeb00-afe4-11ea-9127-880c9be44c84.png)

**Comment by sinancetinkaya** [comment]
Wait a minute, did some change in config options and saved. After that, the host name appeared.

**Comment by brvphoenix** [comment]
> @brvphoenix I'm using Firefox, disabled cache.
> ![image](https://user-images.githubusercontent.com/2675655/84772991-6deeeb00-afe4-11ea-9127-880c9be44c84.png)

The progressbar's labels `upflow` and `downflow` has been changed to `Upstream` and `Downstream` in the new release. The screenshots have shown that you are not using the latest version. Thus, I'm very sure that there are something wrong in you side.

It is mostly likely that the your browser has not replaced these old cached *.js files.

**Comment by sinancetinkaya** [comment]
yeah they are changed now too 
![image](https://user-images.githubusercontent.com/2675655/84774716-ebb3f600-afe6-11ea-92df-c069e3ad47fd.png)
