### ISSUE TITLE
在最新openwrt中显示问题

### ISSUE THREAD

**Issue by fuqiang03** [brvphoenix/luci-app-wrtbwmon#23]
如图 使用最新的luci编译

![QQ截图20200616231355](https://user-images.githubusercontent.com/26851715/84793220-6f8dd280-b027-11ea-9281-03f0ef3ac173.png)
n = new form.Map('wrtbwmon', '');
		s = n.section(form.NamedSection, 'display', 'luci-app-wrtbwmon', _('Display settings'))
		s.addremove = false;
在这行遇到了问题 改了虽然正常显示 不知道是否会有其他问题

**Comment by brvphoenix** [comment]
Have tested that it works well on openwrt snapshot and can‘t verify the issue you mentioned. Besides, The codes you post don't come from the lastest master branch in this repo.

**Comment by fuqiang03** [comment]
抱歉 貌似弄错了
