### ISSUE TITLE
Insufficient permissions to read UCI configuration.

### ISSUE THREAD

**Issue by storm1er** [brvphoenix/luci-app-wrtbwmon#26]
Hi,

A picture is always better:
![gnome-shell-screenshot-6HI6O0](https://user-images.githubusercontent.com/9821946/89766150-f6c36800-daf7-11ea-8882-a217795eb581.png)

When going to `Network > Usage > Configuration` I'm getting an error: `Insufficient permissions to read UCI configuration.`

In syslog I'm getting some of these
```log
XXXXXXXXXXX cron.err crond[716]: ignoring file 'wrtbwmon' (no such user)
```

Any suggestion?

**Comment by brvphoenix** [comment]
If you use [Kiougar's wrtbwmon](https://github.com/Kiougar/luci-wrtbwmon), please go there for help.
