### ISSUE TITLE
Incompatible with IE11 of Windows10

### ISSUE THREAD

**Issue by fight-fly** [brvphoenix/luci-app-wrtbwmon#32]
Hi. 

Report a bug.

The latest version 2.0.4 seems to have some problems on Internet Explorer 11.

![wrtbwmon](https://user-images.githubusercontent.com/70288629/91828498-cd1edc00-ec72-11ea-9b03-3872eab9c6cd.png)

Can you fix it?
Thank you for your app.

**Comment by brvphoenix** [comment]
Test this [artifact](https://github.com/brvphoenix/luci-app-wrtbwmon/suites/1132305733/artifacts/16156161).
