### ISSUE TITLE
How can I contribute to the "luci-i18n-wrtbwmon-zh-cn_2.0.5-1_all.ipk

### ISSUE THREAD

**Issue by BurgerTown** [brvphoenix/luci-app-wrtbwmon#35]

**Comment by brvphoenix** [comment]
You can just modify the translation files in path [luci-app-wrtbwmon/po](https://github.com/brvphoenix/luci-app-wrtbwmon/blob/master/luci-app-wrtbwmon/po/).

Or you can upload your translation files.
