### ISSUE TITLE
openwrt官方19.07.4版本中使用2.06出现：正在收集数据…

### ISSUE THREAD

**Issue by lfznnzq** [brvphoenix/luci-app-wrtbwmon#37]
电脑、手机均使用chrome浏览器。

只能重启路由器才能正确显示，但是一段时间后又再出现.。。。

![wrtbwmon-1](https://user-images.githubusercontent.com/11658987/95535496-308eed00-0a1b-11eb-8b7a-cd3af0b7368b.png)

![wrtbwmon](https://user-images.githubusercontent.com/11658987/95535520-3ab0eb80-0a1b-11eb-96c7-5400340e7be5.png)

**Comment by brvphoenix** [comment]
@lfznnzq 
When the wrtbwmon can't work well, press the `F12` and get the screenshots just as the example below. Thank you.

![screenshots](https://user-images.githubusercontent.com/30111323/95723460-c2128f00-0ca7-11eb-99a1-84a6633e2596.JPG)

**Comment by lfznnzq** [comment]
> @lfznnzq
> When the wrtbwmon can't work well, press the `F12` and get the screenshots just as the example below. Thank you.
> 
> ![screenshots](https://user-images.githubusercontent.com/30111323/95723460-c2128f00-0ca7-11eb-99a1-84a6633e2596.JPG)

你好，因为已经换用2.03版本（能正常使用），所以暂时无法为2.06提供更多检测（猜测大概是开启与防火墙相关的upnp，而出现的bug）

**Comment by lfznnzq** [comment]
重新尝试了一下。结果如图：

![20201110015643](https://user-images.githubusercontent.com/11658987/98578417-4e8c8d80-22f8-11eb-8efc-9cb2e066287a.png)

**Comment by brvphoenix** [comment]
@lfznnzq 
Unable to confirm this issue, but you can try this attachment anyway.
[luci-app-wrtbwmon.zip](https://github.com/brvphoenix/luci-app-wrtbwmon/files/5523096/luci-app-wrtbwmon.zip)
