### ISSUE TITLE
能否过滤掉 LAN接口自身的显示，强迫症看着很烦躁 

### ISSUE THREAD

**Issue by hyird** [brvphoenix/luci-app-wrtbwmon#38]
![image](https://user-images.githubusercontent.com/31695447/96200127-b8c94100-0f8b-11eb-9a22-d058aab81bdb.png)
![image](https://user-images.githubusercontent.com/31695447/96200139-bf57b880-0f8b-11eb-91ad-33fb7292e303.png)
这就很烦 或者把NA换成 192.168.1.1也成啊

**Comment by hyird** [comment]
一起应该过滤的 不然总流量算出来不对

**Comment by brvphoenix** [comment]
If using the v2.0.6, you can filter out the lan by MAC address.
