### ISSUE TITLE
format 不支持

### ISSUE THREAD

**Issue by doumeki** [brvphoenix/luci-app-wrtbwmon#39]
openwrt 使用的是lean的版本，luci应该还是老款的。
luci-wrtbwmon使用的是1.6.3的版本, 客户端显示不出来。
查看是javascript不支持format的函数。

![image](https://user-images.githubusercontent.com/10527841/97784143-58671000-1bd7-11eb-94f0-6a737bbdc186.png)

![image](https://user-images.githubusercontent.com/10527841/97784227-fb1f8e80-1bd7-11eb-80e4-e7beddd4b8fd.png)

**Comment by brvphoenix** [comment]
Try this attachment.
[luci-app-wrtbwmon.zip](https://github.com/brvphoenix/luci-app-wrtbwmon/files/5524256/luci-app-wrtbwmon.zip)

**Comment by doumeki** [comment]
Good , 感谢
![wrtbwmon](https://user-images.githubusercontent.com/10527841/99268526-3e2c6380-2860-11eb-94bd-5c97e3cdf810.png)

**Comment by brvphoenix** [comment]
https://github.com/brvphoenix/luci-app-wrtbwmon/tree/lua

**Comment by shikeong06** [comment]
<img width="1703" height="615" alt="Image" src="https://github.com/user-attachments/assets/25a52b87-42c9-42a8-9e57-7176d9a4853b" />

why I cant install it on my openwrt?
