### ISSUE TITLE
master 分支luci出错

### ISSUE THREAD

**Issue by project-lede** [brvphoenix/luci-app-wrtbwmon#42]
lean的lede源码，出错：

/usr/lib/lua/luci/controller/wrtbwmon.lua:12: attempt to call global 'view' (a nil value)
stack traceback:
	/usr/lib/lua/luci/controller/wrtbwmon.lua:12: in function 'v'
	/usr/lib/lua/luci/dispatcher.lua:572: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:238: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>

**Comment by brvphoenix** [comment]
You need read the `README.md` and verify the openwrt version you are using.
https://github.com/brvphoenix/luci-app-wrtbwmon/blob/master/README.md
