### ISSUE TITLE
Dark mode GUI needs some fixing

### ISSUE THREAD

**Issue by piterq** [brvphoenix/luci-app-wrtbwmon#55]
There is improper bright background in the header:
![image](https://user-images.githubusercontent.com/59413148/178141230-20aed483-5ab1-4059-8ae8-9075d557bec8.png)

The summary (total) row is hard to read due to grey backgroud:
![image](https://user-images.githubusercontent.com/59413148/178140682-ed0a5d2a-9306-4974-a291-5723aee69504.png)

**Suggested fixes**

**1. Remove this line from details.js:**
```
tc = (pc >= 80 ? 'white' : '#404040');
```

**2. Change this code in wrtbwmon.css file:**
```
.tr.table-totals {
	background: #e0e0e0 !important;
}
```
**to this code:**
```
.tr.table-totals {
	font-weight: bold;
}
```

**Comment by HahahahaChen** [comment]
I think you can make a pull request
