### ISSUE TITLE
[Feature] Persist database

### ISSUE THREAD

**Issue by TimerWolf** [brvphoenix/luci-app-wrtbwmon#57]
Is there no way to persist the database so that not is lost every time when the router restarts ?

**Comment by bcseputetto** [comment]
The default database file save path is under /tmp, which is a memory mount, and it will be lost every time you restart. Change the save path to the hard disk. （Software translation）

**Comment by TimerWolf** [comment]
Can you tell me how i could make this work? As i am not very good as this ?

It would be very neat if it would be in the settings i think the old version got that actually, but less important maybe if its an easy way ti fix...

What i do not understand is why you would like to have statistics if its restart every time upon restart..

**Comment by TimerWolf** [comment]
Aha, you mean to "etc/usage.db"...

Thanks for that!
