### ISSUE TITLE
new-dev在19.07.0上不能正确工作

### ISSUE THREAD

**Issue by QiuSimons** [brvphoenix/luci-app-wrtbwmon#6]
已安装了luci-compact，依然工作异常
在luci中点击，会出错

Failed to execute template dispatcher target for entry '/admin/network/usage/details'.
The called action terminated with an exception:
/usr/lib/lua/luci/template.lua:55: Failed to execute template 'wrtbwmon'.
A runtime error occurred: [string "/usr/lib/lua/luci/view/wrtbwmon.htm"]:3: module 'luci.tools.status' not found:
	no field package.preload['luci.tools.status']
	no file './luci/tools/status.lua'
	no file '/usr/share/lua/luci/tools/status.lua'
	no file '/usr/share/lua/luci/tools/status/init.lua'
	no file '/usr/lib/lua/luci/tools/status.lua'
	no file '/usr/lib/lua/luci/tools/status/init.lua'
	no file './luci/tools/status.so'
	no file '/usr/lib/lua/luci/tools/status.so'
	no file '/usr/lib/lua/loadall.so'
	no file './luci.so'
	no file '/usr/lib/lua/luci.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'require'
	[string "/usr/lib/lua/luci/view/wrtbwmon.htm"]:3: in main chunk
stack traceback:
	[C]: in function 'n'
	/usr/lib/lua/luci/template.lua:55: in function </usr/lib/lua/luci/template.lua:47>
	(tail call): ?
	/usr/lib/lua/luci/dispatcher.lua:744: in function </usr/lib/lua/luci/dispatcher.lua:743>

**Comment by brvphoenix** [comment]
Reference to https://github.com/brvphoenix/luci-app-wrtbwmon/issues/4.

**Comment by QiuSimons** [comment]
> Reference to #4.

thanks for you help.
BTW，since 19.07 stable was official released，will this app get updated to catch the luci change？

**Comment by SimonsQiu** [comment]
> Reference to #4.

Few problem
![1](https://user-images.githubusercontent.com/30074550/72861792-e2f41800-3d05-11ea-8539-6c347d1a515f.jpg)
after save setting
![2](https://user-images.githubusercontent.com/30074550/72861806-ed161680-3d05-11ea-98dd-98a8b9048776.jpg)

another problem, no any data
![3](https://user-images.githubusercontent.com/30074550/72861840-03bc6d80-3d06-11ea-952e-cd86899833a0.jpg)

**Comment by brvphoenix** [comment]
The new openwrt release of 19.07.0 has changed some old lua functions.
It may take some time for me to port to the openwrt 19.07.x.

**Comment by brvphoenix** [comment]
@QiuSimons @SimonsQiu

I have ported the LuCI for openwrt 19.07. You can test the following ipk .

[luci-app-wrtbwmon_2.0-1_all.zip](https://github.com/brvphoenix/luci-app-wrtbwmon/files/4142587/luci-app-wrtbwmon_2.0-1_all.zip)

**Comment by QiuSimons** [comment]
> @QiuSimons @SimonsQiu
> 
> I have ported the LuCI for openwrt 19.07. You can test the following ipk .
> 
> [luci-app-wrtbwmon_2.0-1_all.zip](https://github.com/brvphoenix/luci-app-wrtbwmon/files/4142587/luci-app-wrtbwmon_2.0-1_all.zip)

seems working smoothly here thanks for you efforts.
hope source code will be ready soon so i can complie it to my router

**Comment by xftv5608** [comment]
<*> luci-compat................................. LuCI compatibility libraries       
<*> luci-mod-rpc..................................... LuCI RPC - JSON-RPC API

**Comment by xftv5608** [comment]
构选：

<*> luci-compat................................. LuCI compatibility libraries       
<* > luci-mod-rpc .. .................................... LuCI RPC-JSON-RPC API
