### ISSUE TITLE
[Feature Request] refresh every second

### ISSUE THREAD

**Issue by chuwza** [brvphoenix/luci-app-wrtbwmon#68]
Hello developers, thanks a lot for your luci-app-wrtbwmon!
However, I think refreshing every 2 seconds is still not fast enough, could you please add refreshing every second?
![屏幕截图(267)](https://github.com/brvphoenix/luci-app-wrtbwmon/assets/30049891/703cb1de-3318-4412-bfa4-1a9e5a3c4a3d)

Thank you very much

**Comment by brvphoenix** [comment]
The shorter the duration, the greater the statistical error. This project is not aiming at precise real-time bandwidth monitoring. If you have these demands, please use other corresponding tools.
